### ISSUE TITLE
Create global logger based on winston for example available which is available the StorefrontApiContext

### ISSUE THREAD

**Issue by ResuBaka** [DivanteLtd/storefront-api#22]
## What is the motivation for adding/enhancing this feature?

Currently on most when not all places we use console.log/error/warn for logging. I would thing that a global logger instance based on like winston or an other logging library would improve the over all logging for development and production. 

## What are the acceptance criteria 

- [ ] Global logger instance
- [ ] Log Level configurable in the config file and via environment variable

## Can you complete this feature request by yourself?

- [x] YES
- [ ] NO

**Comment by pkarw** [comment]
Good idea. I like it
