### ISSUE TITLE
Change documentation domain to docs.storefrontapi.com 

### ISSUE THREAD

**Issue by ResuBaka** [DivanteLtd/storefront-api#32]
## What is the motivation for adding/enhancing this feature?

We should have the docs available on the docs.storefrontapi.com domain and not on a subdomain from now.sh.

## What are the acceptance criteria 

- [ ] Have the documentation available on docs.storefrontapi.com

## Can you complete this feature request by yourself?

- [ ] YES
- [x] NO

**Comment by pkarw** [comment]
Done!
