### ISSUE TITLE
"export" in package.json scripts

### ISSUE THREAD

**Issue by undefinederror** [DivanteLtd/storefront-api#44]
## Current behavior
`export` fails on Windows
## Expected behavior
should be replaced with `cross-env` so that it would work

## Steps to reproduce the issue
`yarn run restore7`

## Can you handle fixing this bug by yourself?

- [X] YES
- [ ] NO

## Environment details
- OS: Windows 10
- Node: v10.16.3
- Code Version: 1.11.0-dev

**Comment by ResuBaka** [comment]
Thanks for the Issue.

Here I need to say that this Project does not have a 1.11.0-dev version. That was the version of the vue-storefront-api and I have cleared that last weekend. So we now only have tags for the versions this Project has.

So can you maybe fix that problem in the develop branch.

**Comment by undefinederror** [comment]
Hi @ResuBaka 

Isn't what is currently in master branch version 1.11.0-dev?
https://github.com/DivanteLtd/storefront-api/blob/master/package.json

Btw, develop branch does actually already use `cross-env` in place of `export`

**Comment by ResuBaka** [comment]
This is a problem with how that project started. 

This project startet from the codebase of https://github.com/DivanteLtd/vue-storefront-api and that is why the master has version 1.11.0-dev in the package.json. 

I should try to get the 1.0.0 out asap so we can fix that problem, but there I am not sure how much time I have so I could push the project to that state.

**Comment by ResuBaka** [comment]
The current master has fixed it.
