### ISSUE TITLE
Add `Product.breadcrumbs`and `Category.breadcrumbs` feature

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/storefront-api#7]
## What is the motivation for adding / enhancing this feature?

Having breadcrumbs generated by the API instead of the frontend app is always a nice optimization. We should move the business logick from `vue-storefront` for that and create new function inside `Product` and `Category` resolvers:

- [category breadcrumbs logic](https://github.com/DivanteLtd/vue-storefront/blob/da388792f5ed3706e4094cfefe87e3b1aaa9da9e/core/modules/catalog-next/store/category/actions.ts#L151)
- [product breadcrumbs logic](https://github.com/DivanteLtd/vue-storefront/blob/da388792f5ed3706e4094cfefe87e3b1aaa9da9e/core/modules/catalog/store/product/actions.ts#L48)

The schema for breadcrumbs should be like:

`breadcrumbs: [CategoryBinding]` 

The [CategoryBinding](https://github.com/DivanteLtd/storefront-api/blob/cf9e347f2141971510c27a53aaf86aeb777ea2b4/src/modules/default-catalog/graphql/elasticsearch/product/schema.graphqls#L831) is defined inside the `Product` type.

## What are the acceptance criteria 

- [ ] `Product.breadcrumbs` and `Category.breadcrumbs` available for query

**Comment by gibkigonzo** [comment]
closed by #71
