### ISSUE TITLE
Cannot GET” error in API using Vue.js 

### ISSUE THREAD

**Issue by pradeepmeesam** [DivanteLtd/storefront-api#74]
## Can you handle fixing this bug by yourself?

- [ ] YES
- [ ] NO

## Environment details

- Browser: 
- OS: 
- Node: 
- Code Version:

**Comment by gibkigonzo** [comment]
@pradeepmeesam please give any information about error

**Comment by pradeepmeesam** [comment]
@gibkigonzo thanks for the response.

When I access the vue store front api url (http://localhost:8080/) in browser am getting 

Cannot GET /  Error message.

Please find the attached screenshot 
![Api](https://user-images.githubusercontent.com/30195091/80460823-f8568f00-8951-11ea-8536-94852326c602.PNG)
 
Thanks

**Comment by gibkigonzo** [comment]
@pradeepmeesam API is defined on `/api`. There is nothing on `/`. Maybe we should add info about that on `/` route
