### ISSUE TITLE
Compare with vue-storefront-api

### ISSUE THREAD

**Issue by j209** [DivanteLtd/storefront-api#77]
Hi
What is different between storefront-api and [vue-storefront-api](https://github.com/DivanteLtd/vue-storefront-api)?

**Comment by themreza** [comment]
Storefront-api is the next version with updated tech stack and architecture.
It is also intended to be more agnostic in nature, hence the removal of Vue from the name.

See https://github.com/DivanteLtd/storefront-api/blob/master/README.md#example-use-cases
